### ISSUE TITLE
Add an option not to strip an header ??

### ISSUE THREAD

**Issue by aviatesk** [JunoLab/Weave.jl#197]
It seems that there is no option *not* to strip header from version 0.9.0, but sometimes I want to keep headers in order to work together with other packages like [Markdown Preview Enhanced](https://github.com/shd101wyy/markdown-preview-enhanced)
e.g.: YAML options like this
```
---
### Weave.jl options
options:
    ## output settings
    doctype: github
    # out_path:
    fig_path: figs
    ## default code chunk options
    echo: false
    results: "hidden"
    hold: true
    wrap: false
    include: true
    fig_width: 8
    fig_height: 5
    fig_ext: ".svg"

### MPE options
html:
    embed_local_images: true
    toc: true
toc:
    depth_from: 2
    depth_to: 4
    ordered: true
export_on_save:
    html: true
---
```

Could you add an option not to strip an header ??
