### ISSUE TITLE
[FR] allow specification of `TOC` and related options

### ISSUE THREAD

**Issue by vjd** [JunoLab/Weave.jl#402]
I understand that we can use `pandoc_options` in `weave()` to request a table of contents and other options such as depth. It would be useful to have support for these additional features. An example specification from rmarkdown is here.  

```
---
title: "Habits"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
```
